language: rust
dist: trusty
sudo: true

rust:
  - stable
  - beta

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

script:
  - cargo test --manifest-path=librocksdb-sys/Cargo.toml
  - cargo test

cache:
  directories:
    - $HOME/.cache/
